// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventsource.proto

/*
Package eventsource is a generated protocol buffer package.

It is generated from these files:
	eventsource.proto

It has these top-level messages:
	Query
	Event
	Aggregate
	Ack
*/
package eventsource

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Aggregate_Format int32

const (
	Aggregate_PROTOBUF Aggregate_Format = 0
	Aggregate_JSON     Aggregate_Format = 1
	Aggregate_STRING   Aggregate_Format = 2
)

var Aggregate_Format_name = map[int32]string{
	0: "PROTOBUF",
	1: "JSON",
	2: "STRING",
}
var Aggregate_Format_value = map[string]int32{
	"PROTOBUF": 0,
	"JSON":     1,
	"STRING":   2,
}

func (x Aggregate_Format) String() string {
	return proto.EnumName(Aggregate_Format_name, int32(x))
}
func (Aggregate_Format) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// Message containing query parameters
type Query struct {
	Params map[string]string `protobuf:"bytes,1,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Query) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

// Message containing the event data
type Event struct {
	// Id is a unique key for the event.
	// NOTE: in most cases should be an auto-increment key, as we want to keep
	// events in order, but order can also be achieved by created_at timestamp
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Topic (name) of the event. These should be written in the past tense (user_created)
	Topic string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
	// Aggregate to which the event refers to.
	Aggregate *Aggregate `protobuf:"bytes,3,opt,name=aggregate" json:"aggregate,omitempty"`
	// Priority of the event, where 0 is the highest priority.
	Priority int32 `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	// Signature includes SHA1 signature computed against it's contents and signature of the previous event.
	Signature string `protobuf:"bytes,5,opt,name=signature" json:"signature,omitempty"`
	// Origin of the event. e.g. service name.
	OriginName string `protobuf:"bytes,6,opt,name=origin_name,json=originName" json:"origin_name,omitempty"`
	// Origin of the event. e.g. service ip address / browser.
	OriginIp string `protobuf:"bytes,7,opt,name=origin_ip,json=originIp" json:"origin_ip,omitempty"`
	// Created has the identification of which service has created the event and
	// respective timestamp at which the event ocurred
	Created *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=created" json:"created,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Event) GetAggregate() *Aggregate {
	if m != nil {
		return m.Aggregate
	}
	return nil
}

func (m *Event) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Event) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Event) GetOriginName() string {
	if m != nil {
		return m.OriginName
	}
	return ""
}

func (m *Event) GetOriginIp() string {
	if m != nil {
		return m.OriginIp
	}
	return ""
}

func (m *Event) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

// Message containing the aggregate data.
type Aggregate struct {
	Id       string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Schema   string            `protobuf:"bytes,2,opt,name=schema" json:"schema,omitempty"`
	Version  int64             `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Format   Aggregate_Format  `protobuf:"varint,4,opt,name=format,enum=eventsource.Aggregate_Format" json:"format,omitempty"`
	Data     []byte            `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Aggregate) Reset()                    { *m = Aggregate{} }
func (m *Aggregate) String() string            { return proto.CompactTextString(m) }
func (*Aggregate) ProtoMessage()               {}
func (*Aggregate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Aggregate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Aggregate) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Aggregate) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Aggregate) GetFormat() Aggregate_Format {
	if m != nil {
		return m.Format
	}
	return Aggregate_PROTOBUF
}

func (m *Aggregate) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Aggregate) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Message containing successfully event id
type Ack struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Ack) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Query)(nil), "eventsource.Query")
	proto.RegisterType((*Event)(nil), "eventsource.Event")
	proto.RegisterType((*Aggregate)(nil), "eventsource.Aggregate")
	proto.RegisterType((*Ack)(nil), "eventsource.Ack")
	proto.RegisterEnum("eventsource.Aggregate_Format", Aggregate_Format_name, Aggregate_Format_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EventSourceCommand service

type EventSourceCommandClient interface {
	Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Ack, error)
}

type eventSourceCommandClient struct {
	cc *grpc.ClientConn
}

func NewEventSourceCommandClient(cc *grpc.ClientConn) EventSourceCommandClient {
	return &eventSourceCommandClient{cc}
}

func (c *eventSourceCommandClient) Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/eventsource.EventSourceCommand/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EventSourceCommand service

type EventSourceCommandServer interface {
	Create(context.Context, *Event) (*Ack, error)
}

func RegisterEventSourceCommandServer(s *grpc.Server, srv EventSourceCommandServer) {
	s.RegisterService(&_EventSourceCommand_serviceDesc, srv)
}

func _EventSourceCommand_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSourceCommandServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventsource.EventSourceCommand/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSourceCommandServer).Create(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventSourceCommand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventsource.EventSourceCommand",
	HandlerType: (*EventSourceCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EventSourceCommand_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventsource.proto",
}

// Client API for EventSourceProjection service

type EventSourceProjectionClient interface {
	Get(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	List(ctx context.Context, in *Query, opts ...grpc.CallOption) (EventSourceProjection_ListClient, error)
}

type eventSourceProjectionClient struct {
	cc *grpc.ClientConn
}

func NewEventSourceProjectionClient(cc *grpc.ClientConn) EventSourceProjectionClient {
	return &eventSourceProjectionClient{cc}
}

func (c *eventSourceProjectionClient) Get(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/eventsource.EventSourceProjection/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSourceProjectionClient) List(ctx context.Context, in *Query, opts ...grpc.CallOption) (EventSourceProjection_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EventSourceProjection_serviceDesc.Streams[0], c.cc, "/eventsource.EventSourceProjection/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventSourceProjectionListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventSourceProjection_ListClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventSourceProjectionListClient struct {
	grpc.ClientStream
}

func (x *eventSourceProjectionListClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for EventSourceProjection service

type EventSourceProjectionServer interface {
	Get(context.Context, *Event) (*Event, error)
	List(*Query, EventSourceProjection_ListServer) error
}

func RegisterEventSourceProjectionServer(s *grpc.Server, srv EventSourceProjectionServer) {
	s.RegisterService(&_EventSourceProjection_serviceDesc, srv)
}

func _EventSourceProjection_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSourceProjectionServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventsource.EventSourceProjection/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSourceProjectionServer).Get(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSourceProjection_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventSourceProjectionServer).List(m, &eventSourceProjectionListServer{stream})
}

type EventSourceProjection_ListServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type eventSourceProjectionListServer struct {
	grpc.ServerStream
}

func (x *eventSourceProjectionListServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _EventSourceProjection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventsource.EventSourceProjection",
	HandlerType: (*EventSourceProjectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _EventSourceProjection_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _EventSourceProjection_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eventsource.proto",
}

func init() { proto.RegisterFile("eventsource.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0xc4, 0xb5, 0x27, 0xa5, 0x0a, 0x23, 0x5a, 0x59, 0xe6, 0xa3, 0x91, 0xc5, 0x21,
	0x07, 0xe4, 0x56, 0xa6, 0x20, 0x3e, 0x2e, 0x94, 0xaa, 0xad, 0x8a, 0xa0, 0x2d, 0xdb, 0x72, 0x46,
	0x5b, 0x67, 0x6b, 0x96, 0xd4, 0x5e, 0x6b, 0xbd, 0xa9, 0x14, 0xc4, 0x9f, 0xe0, 0x47, 0xf1, 0xbf,
	0x50, 0xc6, 0x76, 0x9b, 0xa0, 0x70, 0xe0, 0xe6, 0x79, 0xf3, 0xde, 0xec, 0xcc, 0x9b, 0x31, 0xdc,
	0x17, 0x37, 0xa2, 0x30, 0x95, 0x9a, 0xe8, 0x54, 0xc4, 0xa5, 0x56, 0x46, 0x61, 0x6f, 0x0e, 0x0a,
	0xb7, 0x32, 0xa5, 0xb2, 0x6b, 0xb1, 0x4d, 0xa9, 0xcb, 0xc9, 0xd5, 0xb6, 0x91, 0xb9, 0xa8, 0x0c,
	0xcf, 0xcb, 0x9a, 0x1d, 0xfd, 0x80, 0xee, 0xe7, 0x89, 0xd0, 0x53, 0x7c, 0x09, 0x6e, 0xc9, 0x35,
	0xcf, 0xab, 0xc0, 0x1a, 0x38, 0xc3, 0x5e, 0xf2, 0x24, 0x9e, 0x2f, 0x4d, 0x9c, 0xf8, 0x8c, 0x08,
	0x07, 0x85, 0xd1, 0x53, 0xd6, 0xb0, 0xc3, 0xd7, 0xd0, 0x9b, 0x83, 0xb1, 0x0f, 0xce, 0x58, 0x4c,
	0x03, 0x6b, 0x60, 0x0d, 0x7d, 0x36, 0xfb, 0xc4, 0x07, 0xd0, 0xbd, 0xe1, 0xd7, 0x13, 0x11, 0xd8,
	0x84, 0xd5, 0xc1, 0x1b, 0xfb, 0x95, 0x15, 0xfd, 0xb2, 0xa1, 0x7b, 0x30, 0x7b, 0x04, 0xd7, 0xc1,
	0x96, 0x23, 0x12, 0x39, 0xcc, 0x96, 0xa3, 0x99, 0xc6, 0xa8, 0x52, 0xa6, 0xad, 0x86, 0x02, 0xdc,
	0x05, 0x9f, 0x67, 0x99, 0x16, 0x19, 0x37, 0x22, 0x70, 0x06, 0xd6, 0xb0, 0x97, 0x6c, 0x2e, 0x74,
	0xb9, 0xd7, 0x66, 0xd9, 0x1d, 0x11, 0x43, 0xf0, 0x4a, 0x2d, 0x95, 0x96, 0x66, 0x1a, 0x74, 0x06,
	0xd6, 0xb0, 0xcb, 0x6e, 0x63, 0x7c, 0x04, 0x7e, 0x25, 0xb3, 0x82, 0x9b, 0x89, 0x16, 0x41, 0x97,
	0xde, 0xba, 0x03, 0x70, 0x0b, 0x7a, 0x4a, 0xcb, 0x4c, 0x16, 0x5f, 0x0b, 0x9e, 0x8b, 0xc0, 0xa5,
	0x3c, 0xd4, 0xd0, 0x09, 0xcf, 0x05, 0x3e, 0x04, 0xbf, 0x21, 0xc8, 0x32, 0x58, 0xa5, 0xb4, 0x57,
	0x03, 0xc7, 0x25, 0xee, 0xc2, 0x6a, 0xaa, 0x05, 0x37, 0x62, 0x14, 0x78, 0xd4, 0x6b, 0x18, 0xd7,
	0xcb, 0x88, 0xdb, 0x65, 0xc4, 0x17, 0xed, 0x32, 0x58, 0x4b, 0x8d, 0x7e, 0xdb, 0xe0, 0xdf, 0x8e,
	0x31, 0xe7, 0x8b, 0x4f, 0xbe, 0x6c, 0x82, 0x5b, 0xa5, 0xdf, 0x44, 0xce, 0x1b, 0x63, 0x9a, 0x08,
	0x03, 0x58, 0xbd, 0x11, 0xba, 0x92, 0xaa, 0x20, 0x5f, 0x1c, 0xd6, 0x86, 0xf8, 0x02, 0xdc, 0x2b,
	0xa5, 0x73, 0x6e, 0x68, 0xf6, 0xf5, 0xe4, 0xf1, 0x72, 0xc3, 0xe2, 0x43, 0x22, 0xb1, 0x86, 0x8c,
	0x08, 0x9d, 0x11, 0x37, 0x9c, 0x3c, 0x59, 0x63, 0xf4, 0x8d, 0xef, 0xc0, 0xcb, 0x85, 0xe1, 0x84,
	0xbb, 0x74, 0x23, 0x4f, 0xff, 0x51, 0xec, 0x53, 0x43, 0xab, 0x2f, 0xe5, 0x56, 0x15, 0xbe, 0x85,
	0x7b, 0x0b, 0xa9, 0xff, 0xba, 0x96, 0x67, 0xe0, 0xd6, 0x4d, 0xe2, 0x1a, 0x78, 0x67, 0xec, 0xf4,
	0xe2, 0xf4, 0xfd, 0x97, 0xc3, 0xfe, 0x0a, 0x7a, 0xd0, 0xf9, 0x70, 0x7e, 0x7a, 0xd2, 0xb7, 0x10,
	0xc0, 0x3d, 0xbf, 0x60, 0xc7, 0x27, 0x47, 0x7d, 0x3b, 0xda, 0x00, 0x67, 0x2f, 0x1d, 0xcf, 0x0c,
	0x54, 0x63, 0xaa, 0xef, 0x31, 0x5b, 0x8d, 0x93, 0x43, 0x40, 0xba, 0xb8, 0x73, 0x6a, 0x79, 0x5f,
	0xe5, 0x39, 0x2f, 0x46, 0xb8, 0x03, 0xee, 0x3e, 0xf9, 0x8f, 0xb8, 0x30, 0x11, 0x51, 0xc3, 0xfe,
	0xe2, 0x94, 0xe9, 0x38, 0x5a, 0x49, 0x7e, 0xc2, 0xc6, 0x5c, 0x9d, 0x33, 0xad, 0xbe, 0x8b, 0xd4,
	0xcc, 0xfc, 0xde, 0x06, 0xe7, 0x48, 0x98, 0xa5, 0x75, 0x96, 0x60, 0xd1, 0x0a, 0x26, 0xd0, 0xf9,
	0x28, 0xab, 0xbf, 0x15, 0xf4, 0xbf, 0x2d, 0x57, 0xec, 0x58, 0x97, 0x2e, 0x5d, 0xd0, 0xf3, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0xda, 0xf2, 0xa2, 0xfe, 0x03, 0x00, 0x00,
}
